# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logfilter_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Logfilter(object):
    def setupUi(self, Logfilter):
        # Set object name and size for the UI's main window.
        Logfilter.setObjectName("Logfilter")
        Logfilter.resize(585, 808)

        # Setup a central widget for the main window.
        self.centralwidget = QtWidgets.QWidget(Logfilter)
        self.centralwidget.setObjectName("centralwidget")

        # Create a grid layout to organize the widgets in a grid
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")

        # Create a push button for browsing 
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)

        # Create a vertical layout for directory address and label
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        # Create a label for directory
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)

        # Create a text field for directory address
        self.Directory_adress = QtWidgets.QLineEdit(self.centralwidget)
        self.Directory_adress.setObjectName("Directory_adress")
        self.verticalLayout_2.addWidget(self.Directory_adress)

        # Add the vertical layout to the grid layout
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 2)

        # Create another vertical layout for more interactive components.
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")

        # Label for the form.
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)

        # Radio buttons for real-time mode selection
        self.radioButton_real_time = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_real_time.setFont(font)
        self.radioButton_real_time.setObjectName("radioButton_real_time")
        self.verticalLayout.addWidget(self.radioButton_real_time)
        self.radioButton_ = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_.setFont(font)
        self.radioButton_.setObjectName("radioButton_")
        self.verticalLayout.addWidget(self.radioButton_)
        self.gridLayout.addLayout(self.verticalLayout, 3, 0, 1, 2)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 4, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 4, 1, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_4.addWidget(self.textBrowser)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.gridLayout.addLayout(self.verticalLayout_4, 5, 0, 1, 2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_3.addWidget(self.comboBox)
        self.gridLayout.addLayout(self.verticalLayout_3, 2, 0, 1, 2)
        Logfilter.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Logfilter)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 585, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        Logfilter.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Logfilter)
        self.statusbar.setObjectName("statusbar")
        Logfilter.setStatusBar(self.statusbar)
        self.actionOpen_Directory = QtWidgets.QAction(Logfilter)
        self.actionOpen_Directory.setObjectName("actionOpen_Directory")
        self.actionSave_Log = QtWidgets.QAction(Logfilter)
        self.actionSave_Log.setObjectName("actionSave_Log")
        self.actionRecent_Directories = QtWidgets.QAction(Logfilter)
        self.actionRecent_Directories.setObjectName("actionRecent_Directories")
        self.actionExit = QtWidgets.QAction(Logfilter)
        self.actionExit.setObjectName("actionExit")
        self.actionLocal_Check = QtWidgets.QAction(Logfilter)
        self.actionLocal_Check.setObjectName("actionLocal_Check")
        self.actionSharepoint_Check_N_A = QtWidgets.QAction(Logfilter)
        self.actionSharepoint_Check_N_A.setObjectName("actionSharepoint_Check_N_A")
        self.actionabout = QtWidgets.QAction(Logfilter)
        self.actionabout.setObjectName("actionabout")
        self.menuFile.addAction(self.actionOpen_Directory)
        self.menuFile.addAction(self.actionSave_Log)
        self.menuFile.addAction(self.actionRecent_Directories)
        self.menuFile.addAction(self.actionExit)
        self.menuSettings.addAction(self.actionLocal_Check)
        self.menuSettings.addAction(self.actionSharepoint_Check_N_A)
        self.menuHelp.addAction(self.actionabout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Logfilter)
        QtCore.QMetaObject.connectSlotsByName(Logfilter)

    def retranslateUi(self, Logfilter):
        _translate = QtCore.QCoreApplication.translate
        Logfilter.setWindowTitle(_translate("Logfilter", "MainWindow"))
        self.pushButton.setText(_translate("Logfilter", "Browse"))
        self.label.setText(_translate("Logfilter", "Directory: "))
        self.label_3.setText(_translate("Logfilter", "Mode"))
        self.radioButton_real_time.setText(_translate("Logfilter", "Real-time Monitoring"))
        self.radioButton_.setText(_translate("Logfilter", "Full Folder Error Check"))
        self.pushButton_2.setText(_translate("Logfilter", "Start"))
        self.pushButton_3.setText(_translate("Logfilter", "Stop"))
        self.label_4.setText(_translate("Logfilter", " Results / Log"))
        self.label_5.setText(_translate("Logfilter", "Statsus:"))
        self.label_2.setText(_translate("Logfilter", "Last used:"))
        self.menuFile.setTitle(_translate("Logfilter", "File"))
        self.menuSettings.setTitle(_translate("Logfilter", "Settings"))
        self.menuHelp.setTitle(_translate("Logfilter", "Help"))
        self.actionOpen_Directory.setText(_translate("Logfilter", "Open Directory"))
        self.actionSave_Log.setText(_translate("Logfilter", "Save Log"))
        self.actionRecent_Directories.setText(_translate("Logfilter", "Recent Directories"))
        self.actionExit.setText(_translate("Logfilter", "Exit"))
        self.actionLocal_Check.setText(_translate("Logfilter", "Local Check"))
        self.actionSharepoint_Check_N_A.setText(_translate("Logfilter", "Sharepoint Check (N/A)"))
        self.actionabout.setText(_translate("Logfilter", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Logfilter = QtWidgets.QMainWindow()
    ui = Ui_Logfilter()
    ui.setupUi(Logfilter)
    Logfilter.show()
    sys.exit(app.exec_())
